# tx-url-shortener

database:
  engine: "sqlite3"
  user: ""
  password: ""
  port: 0
  name: "db.sqlite3"
listen_address: ":8080"
base_code_length: 5
short_url_prefix: "localhost:8080"
cache_size: 10000000
