# tx-url-shortener

database:
  engine: "sqlite3"
  user: ""
  password: ""
  port: 0
  name: "db.sqlite3"
listen_address: ":8080"
# For CSRF protection.
secret: "uncQbYcM9CEv+pLnx55x4pZKYSUN2Xyo"
# Value must be smaller than or equal to 11.
base_code_length: 5
short_url_prefix: "localhost:8080"
# Cache size in bytes.
# Default: 104857600 (100 MiB)
cache_size: 104857600